name: Test vladdoster config

on:
  push:
    paths:
      - .github/workflows/test_configs.yml
      - Dockerfile
      - vladdoster/.zshrc

jobs:
  test_zshrc_config:
    strategy:
      matrix:
        author: [vladdoster, numToStr]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Test ${{ matrix.version }}'s config
        run: |
          docker build \
            --build-arg FOLDER="${{ matrix.version }}" \
            --build-arg TERM="${TERM}" \
            -t "zplg-configs:${{ matrix.version }}" .
