name: Test vladdoster config

on:
  push:
    paths:
      - .github/workflows/test_configs.yml
      - Dockerfile
      - vladdoster/.zshrc

jobs:
  test_vladdoster_config:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: .
          push: false
          file: Dockerfile
          tags: "zplg-configs:vladdoster"
          build-args: |
            FOLDER="vladdoster"
            TERM="${TERM}"
